const data = "{
    "m2": [
        {
            "id": "16233",
            "name": "วรินทร",
            "surname": "ชวลิต",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "7",
            "excel": "15",
            "final exam": "14.13",
            "profileImage": "#9FAD69"
        },
        {
            "id": "16238",
            "name": "ธัญมน",
            "surname": "กิตติญาณ",
            "portfolio": "8",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "10.72222222",
            "profileImage": "#B1A2E"
        },
        {
            "id": "16251",
            "name": "ภัสสร",
            "surname": "ฮัดเจสสัน",
            "portfolio": "8",
            "bmi": "15",
            "comp_design": "10",
            "final exam": "8.944444444",
            "profileImage": "#DFEA5D"
        },
        {
            "id": "16267",
            "name": "ธนิดา",
            "surname": "ธีระปัญญาพงศ์",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "excel": "10",
            "final exam": "8.055555556",
            "profileImage": "#F2C372"
        },
        {
            "id": "16268",
            "name": "ธิญาดา",
            "surname": "พานิชชีวะ",
            "portfolio": "9",
            "bmi": "13",
            "comp_design": "10",
            "final exam": "8.56",
            "profileImage": "#DA135"
        },
        {
            "id": "16270",
            "name": "นันทิกานต์",
            "surname": "นวะบุศย์",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "11.69444444",
            "profileImage": "#81E142"
        },
        {
            "id": "16272",
            "name": "ไอยวริญ",
            "surname": "คุณวุฒิ",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "excel": "15",
            "final exam": "10.76666667",
            "profileImage": "#FB2DA4"
        },
        {
            "id": "16277",
            "name": "พิมพ์รตา",
            "surname": "เขมธร",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "excel": "15",
            "final exam": "11.05555556",
            "profileImage": "#16E2DA"
        },
        {
            "id": "16278",
            "name": "เพชรชมพู",
            "surname": "ภู่ชนะกิจ",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "11.11111111",
            "profileImage": "#70ADC1"
        },
        {
            "id": "16286",
            "name": "อันดา",
            "surname": "ภักดี",
            "portfolio": "8",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "18.33333333",
            "profileImage": "#B03779"
        },
        {
            "id": "16288",
            "name": "เอริณ",
            "surname": "วงศ์อนันต์",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "19",
            "profileImage": "#527D64"
        },
        {
            "id": "16290",
            "name": "กาญา",
            "surname": "เหมเวช",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "final exam": "10.5",
            "profileImage": "#25CA2E"
        },
        {
            "id": "16301",
            "name": "ทัชชกร",
            "surname": "กุลพัฒน์กานนท์",
            "portfolio": "9",
            "bmi": "7",
            "comp_design": "10",
            "excel": "15",
            "final exam": "7.677777778",
            "profileImage": "#298503"
        },
        {
            "id": "16304",
            "name": "ปารมี",
            "surname": "อุทารวุฒิพงศ์",
            "portfolio": "10",
            "bmi": "7",
            "comp_design": "10",
            "excel": "15",
            "final exam": "13.11111111",
            "profileImage": "#D5402D"
        },
        {
            "id": "16311",
            "name": "ภาณิชา",
            "surname": "ฮัดเจสสัน",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "14.88888889",
            "profileImage": "#38F894"
        },
        {
            "id": "16326",
            "name": "ตรีชยา",
            "surname": "หล่อปิ่นมณี",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "14.44444444",
            "profileImage": "#C4C13B"
        },
        {
            "id": "16329",
            "name": "นัคมน",
            "surname": "ตั้งจิตตรง",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "12.37777778",
            "profileImage": "#F3A12F"
        },
        {
            "id": "16332",
            "name": "นีราภา",
            "surname": "เวชยันต์วิวัฒน์",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "9.722222222",
            "profileImage": "#87992C"
        },
        {
            "id": "16341",
            "name": "ศรุดา",
            "surname": "เอื้อบุญญาวัฒน์",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "final exam": "10.32222222",
            "profileImage": "#E3A2CE"
        },
        {
            "id": "16455",
            "name": "กานต์รวี",
            "surname": "กัมมารังกูร",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "9.611111111",
            "profileImage": "#08E5A"
        },
        {
            "id": "16457",
            "name": "กิติญาดา",
            "surname": "นาฑีสุวรรณ",
            "portfolio": "8",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "14.77777778",
            "profileImage": "#BEAD50"
        },
        {
            "id": "16461",
            "name": "ชนิดาภา",
            "surname": "กัลยาวินัย",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "final exam": "11.15555556",
            "profileImage": "#95F811"
        },
        {
            "id": "16467",
            "name": "ทิพย์วิภา",
            "surname": "ภูพิพัฒน์ผล",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "15.44444444",
            "profileImage": "#314475"
        },
        {
            "id": "16476",
            "name": "สาริศา",
            "surname": "หวังธรรมบุญ",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "5.744444444",
            "profileImage": "#C9BE4C"
        },
        {
            "id": "16618",
            "name": "แพตรี",
            "surname": "จวบสมัย",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "final exam": "8.277777778",
            "profileImage": "#95D4FD"
        },
        {
            "id": "17388",
            "name": "พรกมล",
            "surname": "เสนาลักษณ์",
            "portfolio": "5",
            "bmi": "7",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "7.3",
            "profileImage": "#A871A1"
        },
        {
            "id": "17915",
            "name": "ปรวีร์",
            "surname": "โชคครรชิตไชย",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "excel": "15",
            "final exam": "20",
            "profileImage": "#0878EA"
        },
        {
            "id": "17916",
            "name": "พิมพ์ลภัส",
            "surname": "ดุริยภัณฑปกรณ์",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "excel": "15",
            "final exam": "12.44444444",
            "profileImage": "#F05230"
        },
        {
            "id": "18206",
            "name": "ณัฐวรา",
            "surname": "อินทร์ใหม่",
            "portfolio": "9",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "12.33333333",
            "profileImage": "#4F592D"
        },
        {
            "id": "18211",
            "name": "ปรียนิตย์",
            "surname": "เพชรแสงใสสกุล",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "17.33333333",
            "profileImage": "#1F678B"
        },
        {
            "id": "18214",
            "name": "มนสิชา",
            "surname": "โลพันธ์ศรี",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "19",
            "profileImage": "#82FABD"
        },
        {
            "id": "18226",
            "name": "ภัทรวดี",
            "surname": "ประเสริฐสิทธิ์",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "10.66666667",
            "profileImage": "#1BD32E"
        },
        {
            "id": "18228",
            "name": "ญาดา",
            "surname": "ไพบูลย์เกษมสุทธิ",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "15.72222222",
            "profileImage": "#5D4F07"
        },
        {
            "id": "18239",
            "name": "ปารดา",
            "surname": "พรหมบุรมย์",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "13.1",
            "profileImage": "#C60729"
        },
        {
            "id": "18296",
            "name": "ณัฐณิชา",
            "surname": "บำรุงผล",
            "portfolio": "9",
            "bmi": "7",
            "comp_design": "10",
            "final exam": "9.888888889",
            "profileImage": "#D432D"
        },
        {
            "id": "18298",
            "name": "พิชชา",
            "surname": "อุดมวีรเกษม",
            "portfolio": "9.5",
            "bmi": "7",
            "comp_design": "10",
            "excel": "15",
            "final exam": "15.55555556",
            "profileImage": "#1D9E55"
        },
        {
            "id": "16235",
            "name": "ณัฐกิตินี",
            "surname": "พ่วงจินดา",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "14.27777778",
            "profileImage": "#242968"
        },
        {
            "id": "16248",
            "name": "พาขวัญ",
            "surname": "ลีละวัฒนพันธ์",
            "portfolio": "8.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "14.85555556",
            "profileImage": "#FBF3F"
        },
        {
            "id": "16256",
            "name": "สิชา",
            "surname": "สาริกะภูติ",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "18.22222222",
            "profileImage": "#39D0C3"
        },
        {
            "id": "16257",
            "name": "อลิสา",
            "surname": "ลิมปะพันธุ์",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "17",
            "profileImage": "#105F99"
        },
        {
            "id": "16258",
            "name": "ปัณฑารีย์",
            "surname": "เบญจฤทธิ์",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "excel": "15",
            "final exam": "16.33333333",
            "profileImage": "#042C80"
        },
        {
            "id": "16261",
            "name": "พิชญาภา",
            "surname": "เสวิกุล",
            "portfolio": "9",
            "bmi": "7",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "10.5",
            "profileImage": "#F5773B"
        },
        {
            "id": "16265",
            "name": "ณัฏฐกานต์",
            "surname": "วัจน์ประภาศักดิ์",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "12.71111111",
            "profileImage": "#ADB763"
        },
        {
            "id": "16271",
            "name": "ปณาลี",
            "surname": "ปฐมบุรุษรัตน์",
            "portfolio": "10",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "8",
            "excel": "15",
            "final exam": "7.8",
            "profileImage": "#9B1F65"
        },
        {
            "id": "16276",
            "name": "พราวรวี",
            "surname": "ใจมีธรรมดี",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "excel": "15",
            "final exam": "15",
            "profileImage": "#B8E5D7"
        },
        {
            "id": "16279",
            "name": "มนปริยา",
            "surname": "ยะรังษี",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "7",
            "excel": "15",
            "final exam": "12.88888889",
            "profileImage": "#AF2FF4"
        },
        {
            "id": "16293",
            "name": "จรัสกร",
            "surname": "ตั้งฤทัยวานิชย์",
            "portfolio": "5",
            "bmi": "7",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "14.77777778",
            "profileImage": "#1ED5B"
        },
        {
            "id": "16294",
            "name": "ฐิติกาญจน์",
            "surname": "เลิศคัมภีร์ศีล",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "final exam": "15.66666667",
            "profileImage": "#B9754A"
        },
        {
            "id": "16305",
            "name": "ปาลิดา",
            "surname": "เชี่ยวสงวน",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "7.722222222",
            "profileImage": "#A2EFDB"
        },
        {
            "id": "16313",
            "name": "ฐิตินาถ์",
            "surname": "สุวรรณประทีป",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "12.38888889",
            "profileImage": "#61EE4A"
        },
        {
            "id": "16319",
            "name": "เกรซ",
            "surname": "อธิคมรัตนกุล",
            "portfolio": "8",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "8",
            "excel": "15",
            "final exam": "14.61111111",
            "profileImage": "#14CD2C"
        },
        {
            "id": "16331",
            "name": "นันท์นภัส",
            "surname": "บูรณกฤตยากรณ์",
            "portfolio": "8",
            "bmi": "10",
            "comp_design": "10",
            "cc_license": "8",
            "excel": "15",
            "final exam": "8.988888889",
            "profileImage": "#113D39"
        },
        {
            "id": "16339",
            "name": "มาลินณร์",
            "surname": "อินทรพิพัฒน์",
            "portfolio": "8",
            "bmi": "10",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "7.544444444",
            "profileImage": "#564719"
        },
        {
            "id": "16342",
            "name": "ศิรภัสสร",
            "surname": "ถาวรไชยโสภณ",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "16.88888889",
            "profileImage": "#7418B8"
        },
        {
            "id": "16343",
            "name": "ศุภิชยา",
            "surname": "ลิขนะพิชิตกุล",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "excel": "15",
            "final exam": "13.27777778",
            "profileImage": "#89DC19"
        },
        {
            "id": "16345",
            "name": "สุชนาพัทธ์",
            "surname": "วงศ์วรารักษ์",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "10.22222222",
            "profileImage": "#8469D6"
        },
        {
            "id": "16458",
            "name": "ลลิลลักษมิ์",
            "surname": "จักษ์ตรีมงคล",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "8",
            "excel": "15",
            "final exam": "16.22222222",
            "profileImage": "#DDDA3"
        },
        {
            "id": "16472",
            "name": "ภัทริดา",
            "surname": "บุญฤทธิ์ฤทัยกุล",
            "portfolio": "8",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "8",
            "excel": "15",
            "final exam": "13.22222222",
            "profileImage": "#DAFDB6"
        },
        {
            "id": "16474",
            "name": "วรณัชชา",
            "surname": "วิศิษฎ์บัณฑิตกุล",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "17.33333333",
            "profileImage": "#8F5868"
        },
        {
            "id": "17076",
            "name": "ณิชาภา",
            "surname": "บัณฑิตมหากุล",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "13.3",
            "profileImage": "#F41EEF"
        },
        {
            "id": "17378",
            "name": "รดา",
            "surname": "ศยามานนท์",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "excel": "15",
            "final exam": "8.666666667",
            "profileImage": "#C0E463"
        },
        {
            "id": "17472",
            "name": "ภัสกา",
            "surname": "โภคทวี",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "17.88888889",
            "profileImage": "#4AB444"
        },
        {
            "id": "17483",
            "name": "พิมลพร",
            "surname": "เสนาลักษณ์",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "final exam": "15.98888889",
            "profileImage": "#AE9A6"
        },
        {
            "id": "17908",
            "name": "ณัฐธยากรณ์",
            "surname": "แสงสว่าง",
            "portfolio": "5",
            "bmi": "7",
            "comp_design": "10",
            "cc_license": "9",
            "final exam": "7.944444444",
            "profileImage": "#DFF6C1"
        },
        {
            "id": "17912",
            "name": "ฐิติชญาน์",
            "surname": "ศิริเศรษฐ์",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "19.22222222",
            "profileImage": "#18C389"
        },
        {
            "id": "18208",
            "name": "ณัฏฐ์ฐรฎา",
            "surname": "ชาญเลขาบริรักษ์",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "11.71111111",
            "profileImage": "#5E43B3"
        },
        {
            "id": "18210",
            "name": "มุกอันดา",
            "surname": "ณ ระนอง",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "11.55555556",
            "profileImage": "#4915DA"
        },
        {
            "id": "18212",
            "name": "ศุภาพิชญ์",
            "surname": "หงสกุล",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "final exam": "13.05555556",
            "profileImage": "#B9DB01"
        },
        {
            "id": "18215",
            "name": "ภคภรณ์",
            "surname": "โอสุวรรณรัตน์",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "9.988888889",
            "profileImage": "#3BB560"
        },
        {
            "id": "18216",
            "name": "ภูวริศา",
            "surname": "วนาสันตกุล",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "16.88888889",
            "profileImage": "#461E73"
        },
        {
            "id": "18227",
            "name": "สลิลฑิพย์",
            "surname": "ศรีธราดล",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "19.88888889",
            "profileImage": "#97CBF2"
        },
        {
            "id": "18231",
            "name": "รมิดา",
            "surname": "ปียาชัยประภา",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "16.66666667",
            "profileImage": "#41A63F"
        },
        {
            "id": "18234",
            "name": "สุวพิชญ์",
            "surname": "แสงงาม",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "13.38888889",
            "profileImage": "#7846C5"
        },
        {
            "id": "18236",
            "name": "ษษธร",
            "surname": "สถิตย์พรัญชัย",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "8.777777778",
            "profileImage": "#A66759"
        },
        {
            "id": "18305",
            "name": "พีรนุช",
            "surname": "เลิศวงศ์เสถียร",
            "portfolio": "9",
            "bmi": "10",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "11.5",
            "profileImage": "#152002"
        },
        {
            "id": "16236",
            "name": "ณัฐชญา เจสสิก้า  จิรสันติ์",
            "portfolio": "8",
            "bmi": "15",
            "comp_design": "10",
            "excel": "15",
            "final exam": "19.88888889",
            "profileImage": "#D1BD1"
        },
        {
            "id": "16239",
            "name": "ธนัชวนันท์",
            "surname": "สินไชยรัตนากุล",
            "portfolio": "5",
            "bmi": "13",
            "comp_design": "10",
            "excel": "15",
            "final exam": "9.888888889",
            "profileImage": "#23C6D2"
        },
        {
            "id": "16242",
            "name": "ปุณรดา",
            "surname": "ธีรชินภัทร์",
            "portfolio": "9",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "11.48888889",
            "profileImage": "#AF3ED5"
        },
        {
            "id": "16243",
            "name": "พรินทร์อร",
            "surname": "สุทธิสัมพัทน์",
            "portfolio": "5",
            "bmi": "7",
            "comp_design": "10",
            "final exam": "6.055555556",
            "profileImage": "#63B288"
        },
        {
            "id": "16246",
            "name": "พอดี",
            "surname": "ธาราไชย",
            "portfolio": "10",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "9.055555556",
            "profileImage": "#4E142E"
        },
        {
            "id": "16249",
            "name": "พิรดา",
            "surname": "ระมิงค์วงศ์",
            "portfolio": "8.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "8",
            "excel": "15",
            "final exam": "11.27777778",
            "profileImage": "#B5A043"
        },
        {
            "id": "16253",
            "name": "รดา",
            "surname": "วงศ์การุณย์",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "8",
            "excel": "15",
            "final exam": "13.77777778",
            "profileImage": "#818DCD"
        },
        {
            "id": "16283",
            "name": "วริษฐา",
            "surname": "ศรีธัญญรัตน์",
            "portfolio": "8.5",
            "bmi": "13",
            "comp_design": "10",
            "excel": "15",
            "final exam": "10.78888889",
            "profileImage": "#E21E28"
        },
        {
            "id": "16292",
            "name": "เกศแก้ว",
            "surname": "วัชรพันธ์ธร",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "18",
            "profileImage": "#F8E7DC"
        },
        {
            "id": "16298",
            "name": "นิรดา",
            "surname": "ธีระรัตน์",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "excel": "15",
            "final exam": "18.44444444",
            "profileImage": "#FC6595"
        },
        {
            "id": "16299",
            "name": "ณัฐปภัสร์",
            "surname": "รุ่งโรจน์สาคร",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "7",
            "excel": "15",
            "final exam": "17.33333333",
            "profileImage": "#1C065A"
        },
        {
            "id": "16300",
            "name": "ณัฐมน",
            "surname": "เจ็งสืบสันต์",
            "portfolio": "9.5",
            "bmi": "13",
            "comp_design": "10",
            "final exam": "18.66666667",
            "profileImage": "#68CA67"
        },
        {
            "id": "16306",
            "name": "เปี่ยมขวัญ",
            "surname": "ปัณฑวังกูร",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "19.33333333",
            "profileImage": "#411FC9"
        },
        {
            "id": "16307",
            "name": "พริมา",
            "surname": "สุระดรุณศรี",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "17.52222222",
            "profileImage": "#8F0214"
        },
        {
            "id": "16309",
            "name": "ภัณฑิรา",
            "surname": "สหขุน",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "final exam": "14.66666667",
            "profileImage": "#C5D8F5"
        },
        {
            "id": "16316",
            "name": "อภิชญา",
            "surname": "เชาวนศิริกิจ",
            "portfolio": "8",
            "bmi": "7",
            "comp_design": "10",
            "excel": "15",
            "final exam": "13.27777778",
            "profileImage": "#703AA2"
        },
        {
            "id": "16322",
            "name": "ชนุตต์ดา",
            "surname": "เดชธำรง",
            "portfolio": "9",
            "bmi": "7",
            "comp_design": "10",
            "excel": "15",
            "final exam": "12.27777778",
            "profileImage": "#B3C54F"
        },
        {
            "id": "16333",
            "name": "ปุณณภัสสร",
            "surname": "ทรงสุโรจน์",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "17.55555556",
            "profileImage": "#F2C119"
        },
        {
            "id": "16335",
            "name": "พลอยปภัส",
            "surname": "ขจายศรสิทธิ์",
            "portfolio": "8",
            "bmi": "15",
            "comp_design": "10",
            "final exam": "17.77777778",
            "profileImage": "#F67258"
        },
        {
            "id": "16336",
            "name": "พิชชาภรณ์",
            "surname": "อังกุรัตน์",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "13.55555556",
            "profileImage": "#084C60"
        },
        {
            "id": "16337",
            "name": "ภัคกร",
            "surname": "จิตต์อนงค์",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "18",
            "profileImage": "#9B65D5"
        },
        {
            "id": "16340",
            "name": "วรธิดา ",
            "surname": "รัชตะสังข์",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "9.055555556",
            "profileImage": "#A49CCC"
        },
        {
            "id": "16346",
            "name": "อชิรญา",
            "surname": "ยั่งยืนพงษ์",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "14.27777778",
            "profileImage": "#CEC486"
        },
        {
            "id": "16460",
            "name": "ชญากาญจน์",
            "surname": "โชติวิทยารัตน์",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "8",
            "excel": "15",
            "final exam": "15.22222222",
            "profileImage": "#D63EBD"
        },
        {
            "id": "16462",
            "name": "ชลกร",
            "surname": "ณ ระนอง",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "19.22222222",
            "profileImage": "#525ACE"
        },
        {
            "id": "16464",
            "name": "ฐิติรัตน์",
            "surname": "ศิริจรรยากุล",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "10",
            "profileImage": "#03E004"
        },
        {
            "id": "16478",
            "name": "อริญชยา",
            "surname": "กิจพยัคฆ์",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "excel": "15",
            "final exam": "13.5",
            "profileImage": "#5DF16F"
        },
        {
            "id": "17182",
            "name": "ลภัสรดา",
            "surname": "ชีพสัตยากร",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "9.555555556",
            "profileImage": "#98D6EC"
        },
        {
            "id": "17185",
            "name": "พาดาวัน",
            "surname": "เลิศเลอพันธ์",
            "portfolio": "10",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "14",
            "profileImage": "#524797"
        },
        {
            "id": "17193",
            "name": "ภัทรานิษฐ์",
            "surname": "หล่อยืนยง",
            "portfolio": "9",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "14",
            "profileImage": "#183DD5"
        },
        {
            "id": "17909",
            "name": "ภคมน",
            "surname": "สุธีโสภณ",
            "portfolio": "9",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "15",
            "profileImage": "#C8226E"
        },
        {
            "id": "17913",
            "name": "ศรณ์ฐการณ์",
            "surname": "ตั้งคุรุสรณ์",
            "portfolio": "9.5",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "15.46666667",
            "profileImage": "#BE828F"
        },
        {
            "id": "18207",
            "name": "ปุณยนุช",
            "surname": "โลหะเวช",
            "portfolio": "8.5",
            "bmi": "7",
            "comp_design": "10",
            "cc_license": "8",
            "excel": "15",
            "final exam": "14.83333333",
            "profileImage": "#54C2D3"
        },
        {
            "id": "18213",
            "name": "สิริกร",
            "surname": "วรรุตม์",
            "portfolio": "5",
            "bmi": "7",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "16.83333333",
            "profileImage": "#AF6828"
        },
        {
            "id": "18217",
            "name": "บวรลักษณ์",
            "surname": "จรรยารุ่งโรจน์",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "18.88888889",
            "profileImage": "#271854"
        },
        {
            "id": "18218",
            "name": "ธนิดา",
            "surname": "นิงสานนท์",
            "portfolio": "9",
            "bmi": "7",
            "comp_design": "10",
            "final exam": "7.855555556",
            "profileImage": "#2DE1EE"
        },
        {
            "id": "18219",
            "name": "มินท์ธิตา",
            "surname": "จิรกันต์พงษ์",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "excel": "15",
            "final exam": "14.11111111",
            "profileImage": "#38DD36"
        },
        {
            "id": "18229",
            "name": "ระริน",
            "surname": "ศุภองค์ประภา",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "19.22222222",
            "profileImage": "#698A90"
        },
        {
            "id": "16229",
            "name": "กมลกัญจน์",
            "surname": "บุษบัน",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "14",
            "final exam": "14.05555556",
            "profileImage": "#185561"
        },
        {
            "id": "16231",
            "name": "ขวัญชนก",
            "surname": "วัชรประภาพงศ์",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "0",
            "excel": "15",
            "final exam": "14.38888889",
            "profileImage": "#E169FD"
        },
        {
            "id": "16232",
            "name": "คุณิตา",
            "surname": "ยังสุขสถาพร",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "11.13333333",
            "profileImage": "#5FBB91"
        },
        {
            "id": "16241",
            "name": "ปณินันท์",
            "surname": "จันทรบุตร",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "0",
            "excel": "15",
            "final exam": "14.82222222",
            "profileImage": "#482AF3"
        },
        {
            "id": "16245",
            "name": "พลอยณภัส",
            "surname": "สิริภัสภักดี",
            "portfolio": "10",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "8",
            "excel": "15",
            "final exam": "17.22222222",
            "profileImage": "#A6EC63"
        },
        {
            "id": "16250",
            "name": "ภัณฑิรา",
            "surname": "สุวรรณภาภรณ์",
            "portfolio": "5",
            "bmi": "7",
            "comp_design": "10",
            "cc_license": "0",
            "excel": "15",
            "final exam": "11.88888889",
            "profileImage": "#C75058"
        },
        {
            "id": "16255",
            "name": "วิรัล",
            "surname": "รื่นอารมณ์",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "13",
            "final exam": "13.77777778",
            "profileImage": "#C68CB3"
        },
        {
            "id": "16259",
            "name": "กรวิ",
            "surname": "หัสดินไพศาล",
            "portfolio": "9",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "6.111111111",
            "profileImage": "#899C53"
        },
        {
            "id": "16260",
            "name": "แก้วเกศ",
            "surname": "วัชรพันธ์ธร",
            "portfolio": "8",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "8",
            "excel": "15",
            "final exam": "19",
            "profileImage": "#B769F2"
        },
        {
            "id": "16263",
            "name": "เจตนิพิฐ",
            "surname": "โชตนภูติ",
            "portfolio": "8",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "0",
            "excel": "15",
            "final exam": "9.6",
            "profileImage": "#D2B1A3"
        },
        {
            "id": "16264",
            "name": "ณภัชชา",
            "surname": "แก้วกำเหนิด",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "15.11111111",
            "profileImage": "#3FE00"
        },
        {
            "id": "16269",
            "name": "นัชนันท์",
            "surname": "อนุพันธนันท์",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "17.5",
            "profileImage": "#575408"
        },
        {
            "id": "16273",
            "name": "วรีสา",
            "surname": "ตีระสงกรานต์",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "17.88888889",
            "profileImage": "#C1B015"
        },
        {
            "id": "16274",
            "name": "พราว",
            "surname": "สิมะเสถียร",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "11.65555556",
            "profileImage": "#05C3AD"
        },
        {
            "id": "16281",
            "name": "รดา",
            "surname": "บุณยอาคม",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "0",
            "final exam": "4.466666667",
            "profileImage": "#FCB56F"
        },
        {
            "id": "16282",
            "name": "ลลดา",
            "surname": "ตันติอภิชาต",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "0",
            "excel": "15",
            "final exam": "14.27777778",
            "profileImage": "#89D137"
        },
        {
            "id": "16285",
            "name": "สิริภา",
            "surname": "ฮากิม",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "16.22222222",
            "profileImage": "#7C7220"
        },
        {
            "id": "16289",
            "name": "กัลยกร",
            "surname": "ตรีกมล",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "17",
            "profileImage": "#DDED7A"
        },
        {
            "id": "16291",
            "name": "กุลธิดา",
            "surname": "รักษานาเวศ",
            "portfolio": "10",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "15.44444444",
            "profileImage": "#2C251B"
        },
        {
            "id": "16295",
            "name": "ฐิติพรรณ",
            "surname": "พงษ์สถิตย์พร",
            "portfolio": "8",
            "bmi": "10",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "14",
            "profileImage": "#6CF812"
        },
        {
            "id": "16302",
            "name": "นันท์นภัส",
            "surname": "มานิกบุตร",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "18.88888889",
            "profileImage": "#99F419"
        },
        {
            "id": "16310",
            "name": "ภัทรวลัณณ์",
            "surname": "วรรณยศ",
            "portfolio": "9",
            "bmi": "7",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "13",
            "final exam": "14",
            "profileImage": "#05AC7E"
        },
        {
            "id": "16317",
            "name": "ณัฐฏรวี",
            "surname": "จงประเสริฐ",
            "portfolio": "9",
            "bmi": "10",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "16.33333333",
            "profileImage": "#6172F8"
        },
        {
            "id": "16318",
            "name": "อิศริยา",
            "surname": "นิ่มนวล",
            "portfolio": "9",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "17.18888889",
            "profileImage": "#764177"
        },
        {
            "id": "16320",
            "name": "ขวัญข้าว",
            "surname": "ฉัตรอารยมนตรี",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "11.71111111",
            "profileImage": "#68B91B"
        },
        {
            "id": "16321",
            "name": "จิตต์ปภัสร์",
            "surname": "อรุณสุขสว่าง",
            "portfolio": "9.5",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "14.32222222",
            "profileImage": "#99571B"
        },
        {
            "id": "16328",
            "name": "นภัสวรรณ",
            "surname": "นายเรือ",
            "portfolio": "9",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "19",
            "profileImage": "#0735CF"
        },
        {
            "id": "16338",
            "name": "ภาวิกา",
            "surname": "ฤทธิปรีดานันท์",
            "portfolio": "5",
            "bmi": "7",
            "comp_design": "10",
            "cc_license": "0",
            "final exam": "7.166666667",
            "profileImage": "#EDCF3"
        },
        {
            "id": "16395",
            "name": "บุญนภา",
            "surname": "สัมฤทธิวณิชชา",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "final exam": "20",
            "profileImage": "#389F19"
        },
        {
            "id": "16469",
            "name": "ปินริสา",
            "surname": "เปี่ยมใส",
            "portfolio": "9",
            "bmi": "9",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "13.61111111",
            "profileImage": "#2359CD"
        },
        {
            "id": "16475",
            "name": "วิภานันท์",
            "surname": "เหตระกูล",
            "portfolio": "9",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "11.72222222",
            "profileImage": "#E12C54"
        },
        {
            "id": "16681",
            "name": "กันติชา",
            "surname": "แม้นเหมือน",
            "portfolio": "5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "0",
            "excel": "15",
            "final exam": "14.66666667",
            "profileImage": "#B9C9E9"
        },
        {
            "id": "17910",
            "name": "ภควรรณ",
            "surname": "สุธีโสภณ",
            "portfolio": "9.5",
            "bmi": "13",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "13.33333333",
            "profileImage": "#428FAA"
        },
        {
            "id": "17911",
            "name": "พิมพ์ฐิตา",
            "surname": "กิจถาวรรัตน์",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "17.88888889",
            "profileImage": "#90205B"
        },
        {
            "id": "18209",
            "name": "ศิรดา",
            "surname": "ศิริกันทา",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "9",
            "excel": "15",
            "final exam": "18.77777778",
            "profileImage": "#B87729"
        },
        {
            "id": "18225",
            "name": "เมลิสา",
            "surname": "กอเจริญ",
            "portfolio": "9.5",
            "bmi": "15",
            "comp_design": "10",
            "cc_license": "10",
            "excel": "15",
            "final exam": "18",
            "profileImage": "#A99BB3"
        },
        {
            "id": "18499",
            "name": "ฐิตารีย์",
            "surname": "จงจิตรธนจรัส",
            "portfolio": "5",
            "bmi": "7",
            "comp_design": "10",
            "cc_license": "0",
            "final exam": "7",
            "profileImage": "#ED8574"
        }
    ]
}"